# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    default_locale: en
    translator:
        fallbacks:
            - en

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true
    #desactivation de la protection csrf pour l'exercice
    form:
        csrf_protection: false

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
