controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

info:
    path: /client/prenom/{prenom}
    controller: App\Controller\Client::info
    requirements:
        prenom: '[a-zA-Z]+\w+(-\w+)*'
    methods: GET

home:
    path: /img/home
    controller: App\Controller\ImageController::home

affiche:
    path: /img/data/{fichier}
    controller: App\Controller\ImageController::affiche

register:
    path: /img/home/register
    controller: App\Controller\Register::register

registration_success:
    path: /img/home/register_succes/{login}
    controller: App\Controller\SigninController::registerSuccess


